- hosts: '{{ passed_in_hosts }}'
  vars:
    - airflow_version: 2.0.1
  become: yes
  remote_user: ubuntu
  become_user: root
  tasks:
    - name: install dependencies
      apt:
        update_cache: yes
        name:
          - htop
          - python3-pip
        state: present

    - name: Install AIRFLOW python package
      pip:
        name: apache-airflow
        version: '{{ airflow_version }}'

    - name: Initialize airflow database (airflow db init)
      command: 'airflow db init'

    - name: Create admin user for airflow login
      command: 'airflow users create --username admin --password admin --firstname Peter  --lastname Parker --role Admin --email spiderman@superhero.org'

    - name: Start airflow scheduler in background
      command: airflow scheduler -D

    - name: Start airflow webserver on port 80 in background
      command: airflow webserver -D --port 80
      ignore_errors: True
      register: command_result
      failed_when: "'webserver is already running' in command_result.stderr"
  # - name: install Jenkins
  #   yum:
  #     name: jenkins
  #     state: present

  # - name: stop Jenkins
  #   service:
  #     name: jenkins
  #     state: stopped
  # - name: copy cloned jenkins files to /var/lib/jenkins
  #   copy:
  #     remote_src: yes
  #     src: /tmp/jenkins/jenkins
  #     dest: /var/lib
  # - name: restore jenkins user ownership on /var/lib/jenkins
  #   file:
  #     path: /var/lib/jenkins
  #     state: directory
  #     recurse: yes
  #     owner: jenkins
  # - name: start jenkins
  #   service:
  #     name: jenkins
  #     state: started
  #     enabled: yes
  # - name: wait for jenkins to start completely
  #   shell: result_first=1; while [[ $result_first != 0 ]]; do if [[ `grep 'Jenkins is fully up and running' /var/log/jenkins/jenkins.log` ]]; then result_first=0; else sleep 4;fi;done
  #   register: result
  #   until: result.rc == 0
